# Generated by Django 4.1.7 on 2023-03-31 17:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Pavadinimas')),
                ('slug', models.SlugField(max_length=100)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='recipes_app.category')),
            ],
            options={
                'verbose_name': 'Kategorija',
                'verbose_name_plural': 'Kategorijos',
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Produktas')),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name': 'Ingredientas',
                'verbose_name_plural': 'Ingredientai',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Pavadinimas')),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name': 'Žyma',
                'verbose_name_plural': 'Žymos',
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Sukūrimo data')),
                ('title', models.CharField(max_length=100, verbose_name='Pavadinimas')),
                ('image', models.ImageField(null=True, upload_to='images/', verbose_name='Nuotrauka')),
                ('serves', models.PositiveIntegerField(default=0, verbose_name='Porcijos')),
                ('cook_time', models.PositiveIntegerField(default=0, verbose_name='Gaminimo laikas')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Kiekis')),
                ('measurement_unit', models.TextField(max_length=20, verbose_name='Tekstas')),
                ('directions', models.TextField(verbose_name='Gaminimo eiga')),
                ('notes', models.TextField(verbose_name='Pastabos')),
                ('slug', models.SlugField(unique=True)),
                ('author', models.ForeignKey(blank=True, max_length=50, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipes', to=settings.AUTH_USER_MODEL, verbose_name='Autorius')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipe', to='recipes_app.category')),
                ('ingredients', models.ManyToManyField(related_name='recipe', to='recipes_app.ingredient')),
                ('tags', models.ManyToManyField(related_name='recipe', to='recipes_app.tag')),
            ],
            options={
                'verbose_name': 'Receptas',
                'verbose_name_plural': 'Receptai',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100, verbose_name='El. paštas')),
                ('message', models.TextField(max_length=500, verbose_name='Tekstas')),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='recipes_app.recipe')),
            ],
            options={
                'verbose_name': 'Komentaras',
                'verbose_name_plural': 'Komentarai',
            },
        ),
    ]
