# Generated by Django 4.1.7 on 2023-03-31 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_app', '0002_comment_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Aprašymas'),
        ),
    ]
