# Generated by Django 4.1.7 on 2023-03-31 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_app', '0003_recipe_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeasurementUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Pavadinimas')),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name': 'Mato vienetas',
                'verbose_name_plural': 'Mato vienetai',
            },
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='ingredients',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='measurement_unit',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='quantity',
        ),
        migrations.CreateModel(
            name='RecipeIngredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Kiekis')),
                ('ingredient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipes_app.ingredient', verbose_name='Ingredientas')),
                ('measurement_unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipes_app.measurementunit', verbose_name='Mato vienetas')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_ingredient', to='recipes_app.recipe', verbose_name='Receptas')),
            ],
        ),
    ]
