# Generated by Django 4.1.7 on 2023-03-31 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_app', '0004_measurementunit_remove_recipe_ingredients_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipeingredients',
            options={'verbose_name': 'Recepto ingredientas', 'verbose_name_plural': 'Recepto ingredientai'},
        ),
    ]
