# Generated by Django 4.1.7 on 2023-03-31 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_app', '0005_alter_recipeingredients_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-create_at'], 'verbose_name': 'Komentaras', 'verbose_name_plural': 'Komentarai'},
        ),
    ]
