# Generated by Django 4.1.7 on 2023-04-10 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_app', '0006_alter_comment_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredients',
            name='quantity',
            field=models.FloatField(default=0, verbose_name='Kiekis'),
        ),
    ]
