# Generated by Django 4.1.7 on 2023-04-11 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_app', '0007_alter_recipeingredients_quantity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['-create_at'], 'verbose_name': 'Receptas', 'verbose_name_plural': 'Receptai'},
        ),
    ]
