# Generated by Django 4.1.7 on 2023-04-15 16:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_app', '0009_info_alter_recipe_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100, verbose_name='El. paštas')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Pridėjimo data')),
            ],
            options={
                'verbose_name': 'Prenumeratos gavėjas',
                'verbose_name_plural': 'Prenumeratos gavėjai',
                'ordering': ['email'],
            },
        ),
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ['name'], 'verbose_name': 'Ingredientas', 'verbose_name_plural': 'Ingredientai'},
        ),
        migrations.AlterModelOptions(
            name='measurementunit',
            options={'ordering': ['name'], 'verbose_name': 'Mato vienetas', 'verbose_name_plural': 'Mato vienetai'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['name'], 'verbose_name': 'Žyma', 'verbose_name_plural': 'Žymos'},
        ),
        migrations.AlterField(
            model_name='comment',
            name='create_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Sukūrimo data'),
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255, verbose_name='Tema')),
                ('body', models.TextField(verbose_name='Tekstas')),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Published', 'Published')], max_length=10, verbose_name='Statusas')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Sukūrimo data')),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='Atnaujinimo data')),
                ('email', models.ManyToManyField(to='recipes_app.newsletteruser')),
            ],
            options={
                'verbose_name': 'Prenumerata',
                'verbose_name_plural': 'Prenumerata',
                'ordering': ['-created'],
            },
        ),
    ]
