# Generated by Django 4.1.7 on 2023-04-16 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_app', '0010_newsletteruser_alter_ingredient_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsletter',
            options={'ordering': ['-created'], 'verbose_name': 'Naujienlaiškis', 'verbose_name_plural': 'Naujienlaiškai'},
        ),
        migrations.AlterModelOptions(
            name='newsletteruser',
            options={'ordering': ['email'], 'verbose_name': 'Naujienlaiškio gavėjas', 'verbose_name_plural': 'Naujienlaiškio gavėjai'},
        ),
    ]
